# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama_title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
        ),
    ]
