# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_drama'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='drama_img',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
