# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170124_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='drama_img',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_img',
        ),
    ]
