# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20170124_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='drama_img',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
